using System;
using System.Collections.Generic;
using Microsoft.Data.Sqlite;

namespace PhotoLibrary.Backend;

public interface IDatabaseManager
{
    string DbPath { get; }
    void RegisterFolderCreatedHandler(Action<string, string> handler);

    void ClearCaches();
    SqliteConnection GetOpenConnection();
    SqliteTransaction BeginTransaction(SqliteConnection connection);
    Task ExecuteWriteAsync(Func<SqliteConnection, SqliteTransaction, Task> action);
    void ExecuteWrite(Action<SqliteConnection, SqliteTransaction> action);
    void Initialize();
    void NormalizeRoots();
    void UpdateFileRootId(string fileId, string newRootId);
    void TouchFile(SqliteConnection connection, SqliteTransaction? transaction, string fileId, long timestamp);
    void TouchFileWithRoot(SqliteConnection connection, SqliteTransaction? transaction, string fileId, string newRootId, long timestamp);
    List<FileEntry> GetFileEntriesForRoot(string rootId, bool includeTouched = false);
    string? GetSetting(string? key);
    void SetSetting(string? key, string? value);
    void SetSettingWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string? key, string? value);
    LibraryInfoResponse GetLibraryInfo(string previewDbPath, string configPath);
    StatsResponse GetGlobalStats();
    PagedPhotosResponse GetPhotosPaged(int limit, int offset, string? rootId = null, bool pickedOnly = false, int rating = 0, string[]? specificIds = null);
    string CreateCollection(string name);
    void DeleteCollection(string collectionId);
    void AddFilesToCollection(string collectionId, IEnumerable<string> fileIds);
    IEnumerable<CollectionResponse> GetCollections();
    IEnumerable<string> GetCollectionFiles(string collectionId);
    void ClearPicked();
    IEnumerable<string> GetPickedIds();
    PagedMapPhotoResponse GetMapPhotos();
    PagedPhotosResponse GetGeotaggedPhotosPaged(int limit, int offset);
    HashSet<string> GetAllFilePathsForRoot(string rootId);
    HashSet<string> GetAllIndexedDirectories();
    string? FindClosestRoot(string absolutePath);
    object? DebugFolder(string rootId);
    object? LocateFile(string fileName);
    int DeduplicateRoots();
    string GetOrCreateBaseRoot(string absolutePath);
    string GetOrCreateBaseRootWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string absolutePath);
    string GetOrCreateChildRoot(string parentId, string name);
    string GetOrCreateChildRootWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string parentId, string name);
    string GetOrCreateHierarchy(SqliteConnection connection, SqliteTransaction transaction, string baseRootId, string baseRootPath, string targetDirPath);
    List<string> GetFileIdsUnderRoot(string rootId, bool recursive);
    List<string> GetStackedFileIdsUnderRoot(string rootId, bool recursive);
    HashSet<string> GetDescendantRootIds(string rootId);
    void UpsertFileEntry(FileEntry entry);
    void UpsertFileEntryWithConnection(SqliteConnection connection, SqliteTransaction? transaction, FileEntry entry);
    void DeleteFileEntryWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string fileId);
    string? GetFileHash(string fileId);
    string? GetFileHashWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string fileId);
    (string? fullPath, int rotation, bool isHidden) GetExportInfo(string fileId);
    string? GetFullFilePath(string fileId);
    string? GetFileRootId(string fileId);
    string? GetFileId(string rootPathId, string fileName);
    string? GetFileIdByPath(string absolutePath);
    string? GetFileIdWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string rootPathId, string fileName);
    void UpdateFileHash(string fileId, string hash);
    void UpdateFileHashWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string fileId, string hash);
    bool FileExistsByHash(string hash);
    bool FileExistsByHashWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string hash);
    (bool exists, DateTime? lastModified) GetExistingFileStatus(string fullPath, SqliteConnection? existingConnection = null);
    bool FileExists(string fullPath, SqliteConnection? existingConnection = null);
    void InsertMetadata(string fileId, IEnumerable<MetadataItem> metadata);
    void InsertMetadataWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string fileId, IEnumerable<MetadataItem> metadata);
    IEnumerable<DirectoryNodeResponse> GetDirectoryTree();
    void SetFolderAnnotation(string folderId, string annotation, string? color = null);
    void ForgetRoot(string rootId);
    List<string> GetFileHashesUnderRoot(string rootId);
    IEnumerable<MetadataItemResponse> GetMetadata(string fileId);
    void SetPicked(string fileId, bool isPicked);
    void SetPickedWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string fileId, bool isPicked);
    void SetRating(string fileId, int rating);
    void SetRatingWithConnection(SqliteConnection connection, SqliteTransaction? transaction, string fileId, int rating);
    IEnumerable<string> Search(SearchRequest req);
    HashSet<string> GetExistingFileNames(string rootId, IEnumerable<string> fileNames);
}