export const constants = {
    pubsub: {
        VIEW_MODE_CHANGED: 'view.mode.changed' as const,
        PHOTO_SELECTED: 'photo.selected' as const,
        PHOTO_UPDATED: 'photo.updated' as const,
        PHOTO_ROTATED: 'photo.rotated' as const,
        PHOTO_PICKED_ADDED: 'photo.picked.added' as const,
        PHOTO_PICKED_REMOVED: 'photo.picked.removed' as const,
        PHOTO_STARRED_ADDED: 'photo.starred.added' as const,
        PHOTO_STARRED_REMOVED: 'photo.starred.removed' as const,
        PHOTO_STARRED_CHANGED: 'photo.starred.changed' as const,
        LIBRARY_REFRESH: 'library.refresh' as const,
        LIBRARY_UPDATED: 'library.updated' as const,
        PHOTO_IMPORTED: 'photo.imported' as const,
        FOLDER_CREATED: 'folder.created' as const,
        FOLDER_PROGRESS: 'folder.progress' as const,
        FOLDER_FINISHED: 'folder.finished' as const,
        FIND_NEW_FILE_FOUND: 'find-new.file-found' as const,
        PREVIEW_GENERATED: 'preview.generated' as const,
        PREVIEW_GENERATING: 'preview.generating' as const,
        PREVIEW_DELETED: 'preview.deleted' as const,
        SEARCH_TRIGGERED: 'search.triggered' as const,
        SHORTCUTS_SHOW: 'shortcuts.show' as const,
        UI_LAYOUT_CHANGED: 'ui.layout.changed' as const,
        UI_NOTIFICATION: 'ui.notification' as const,
        UI_SEARCH_STATUS: 'ui.search.status' as const,
        UI_SHOW_POPOVER: 'ui.show.popover' as const,
        IMPORT_FILE_FINISHED: 'import.file.finished' as const,
        CONNECTION_CHANGED: 'connection.changed' as const,
        RUNTIME_STATS: 'runtime.stats' as const,
    },
    socket: {
        IMAGE: 'image' as const,
        FILE_IMPORTED: 'file.imported' as const,
        FOLDER_CREATED: 'folder.created' as const,
        SCAN_FINISHED: 'scan.finished' as const,
        FOLDER_PROGRESS: 'folder.progress' as const,
        FOLDER_FINISHED: 'folder.finished' as const,
        FIND_NEW_FILE_FOUND: 'find-new.file-found' as const,
        PREVIEW_GENERATED: 'preview.generated' as const,
        PREVIEW_GENERATING: 'preview.generating' as const,
        PREVIEW_DELETED: 'preview.deleted' as const,
        PHOTO_PICKED_ADDED: 'photo.picked.added' as const,
        PHOTO_PICKED_REMOVED: 'photo.picked.removed' as const,
        PHOTO_STARRED_ADDED: 'photo.starred.added' as const,
    }
};
